#!/usr/bin/env python3

"""Fetch the site's three typefaces from Google Fonts and write fonts.css.

    tools/web/site/fonts/fetch-fonts.py

The .woff2 files this downloads are committed beside it, so the site build has
no network dependency and no third-party request at runtime -- a page that
fetches its fonts from fonts.gstatic.com tells Google who is playing IVAN, which
is not a thing a page needs to do to draw a headline. This script exists to
regenerate them, not to run at build time.

Only the `latin` subset of each face is kept. Google's CSS serves one @font-face
per unicode-range -- cyrillic, greek, vietnamese and latin-ext for these
families -- and the page has no text outside latin, so the rest is weight the
visitor pays for and never reads.

Both families are SIL Open Font License 1.1:

    Grenze          https://fonts.google.com/specimen/Grenze
    Spectral        https://fonts.google.com/specimen/Spectral
    IBM Plex Mono   https://fonts.google.com/specimen/IBM+Plex+Mono
"""

import os
import re
import sys
import urllib.request

# The families and weights the site actually uses. Adding a weight here without
# using it costs a file on every first load, so this list is deliberately short:
# a display face at two weights, a text face at two, and a mono at two.
FAMILIES = [
    ("Grenze", "wght@600;700", "grenze"),
    ("Spectral", "wght@400;600", "spectral"),
    ("IBM+Plex+Mono", "wght@400;600", "plexmono"),
]

# Google serves woff2 only to a browser it recognises. With a Python UA it
# answers with truetype, which is roughly twice the size for no benefit.
AGENT = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
         "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

# The latin block, as Google writes it. Matched rather than parsed: the exact
# string is stable across families, and a near-miss should fail loudly here
# rather than silently ship the Vietnamese subset.
LATIN = "U+0000-00FF"

FACE = re.compile(r"@font-face\s*\{(.*?)\}", re.S)


def get(url):
    request = urllib.request.Request(url, headers={"User-Agent": AGENT})

    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


def field(block, name):
    found = re.search(name + r":\s*([^;]+);", block)

    return found.group(1).strip() if found else None


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    rules = []

    # Keyed by URL, because a variable font answers every weight in its range
    # with the same file: Grenze 600 and Grenze 700 are one download, and
    # writing it twice would put a copy of it on every first load for nothing.
    files = {}

    for family, axis, slug in FAMILIES:
        url = ("https://fonts.googleapis.com/css2?family=%s:%s&display=swap"
               % (family, axis))
        css = get(url).decode("utf-8")
        kept = 0

        for block in FACE.findall(css):
            # The unicode-range comment above each block is what names the
            # subset; the range itself is what we match, since the comment is
            # not part of the block.
            if LATIN not in (field(block, "unicode-range") or ""):
                continue

            source = field(block, "src")
            href = re.search(r"url\((https://[^)]+\.woff2)\)", source or "")

            if not href:
                sys.exit("no woff2 in src for %s: %s" % (family, source))

            weight = field(block, "font-weight") or "400"
            style = field(block, "font-style") or "normal"
            name = files.get(href.group(1))

            if name:
                print("%-28s (same file as %s)" % (weight + " " + family, name))
            else:
                name = "%s-%s%s.woff2" % (slug, weight,
                                          "" if style == "normal" else "-" + style)

                with open(os.path.join(here, name), "wb") as handle:
                    handle.write(get(href.group(1)))

                files[href.group(1)] = name
                print("%-28s %s" % (name, href.group(1)))

            rules.append(
                "@font-face {\n"
                "  font-family: '%s';\n"
                "  font-style: %s;\n"
                "  font-weight: %s;\n"
                "  font-display: swap;\n"
                "  src: url('%s') format('woff2');\n"
                "  unicode-range: %s;\n"
                "}\n" % (field(block, "font-family").strip("'\""), style,
                         weight, name, field(block, "unicode-range")))

            kept += 1

        if not kept:
            sys.exit("no latin subset found for %s -- has Google's CSS changed "
                     "shape? Check the unicode-range match." % family)

    with open(os.path.join(here, "fonts.css"), "w") as handle:
        handle.write("/* Generated by fetch-fonts.py. Do not edit.\n"
                     " * Grenze, Spectral and IBM Plex Mono, latin subset,\n"
                     " * SIL Open Font License 1.1. */\n\n")
        handle.write("\n".join(rules))

    print("\n%d faces over %d files -> fonts.css" % (len(rules), len(files)))


if __name__ == "__main__":
    main()
